### ISSUE TITLE
randomInt is not a function

### ISSUE THREAD

**Issue by asecaida** [sachin-upmanyu/ods-command-center#1]
Thanks for this, it's amazing!  I was trying to run it locally and I keep getting this error when trying to authenticate, any ideas?  I was able to replace randomInt with Math.random and it works.
![image](https://user-images.githubusercontent.com/3698208/119270664-a7e04e00-bbb2-11eb-9c20-e74a2fa80419.png)

**Comment by sachin-upmanyu** [comment]
Thanks @asecaida.
Can you try to rebuild the client `cd client && npm run build`.
It might be possible that build step had some errors.

**Comment by asecaida** [comment]
That seems to have done it, thanks.  Can't wait to see the upcoming features, this is an awesome tool!!!

**Comment by asecaida** [comment]
Doesn't seem to have helped.  Maybe it's because of my version of node(10.19)?  Regardless, Math.random seems to have worked as a patch for now.  Can't wait to see the upcoming features, you build a very cool tool!!!

**Comment by sachin-upmanyu** [comment]
Thank a lot @asecaida for the support.
I was also able to regenerate this on Node v10.19, it was caused because this crypto.randomInt is available from v12.19 only.
It has been replaced with Math.random and mentioned recommended node version in Readme also.
